-- CreateEnum
CREATE TYPE "loan_transaction_type" AS ENUM ('CREATION', 'EDIT', 'DISBURSEMENT', 'STATE_CHANGE', 'REPAYMENT', 'FEE', 'PENALTY_APPLIED', 'PAYMENT_RESCHEDULE', 'REPAYMENT_ADJUSTMENT', 'FEE_ADJUSTMENT', 'PENALTY_ADJUSTMENT', 'BRANCH_CHANGED', 'DEFERRED_INTEREST_APPLIED', 'DEFERRED_INTEREST_APPLIED_ADJUSTMENT', 'DEFERRED_INTEREST_PAID', 'DEFERRED_INTEREST_PAID_ADJUSTMENT', 'DISBURSEMENT_ADJUSTMENT', 'FEE_CHARGED', 'FEE_LOCKED', 'FEE_REDUCTION_ADJUSTMENT', 'FEE_UNLOCKED', 'FEES_DUE_REDUCED', 'IMPORT', 'INTEREST_APPLIED', 'INTEREST_APPLIED_ADJUSTMENT', 'INTEREST_DUE_REDUCED', 'INTEREST_LOCKED', 'INTEREST_RATE_CHANGED', 'INTEREST_REDUCTION_ADJUSTMENT', 'INTEREST_UNLOCKED', 'PENALTIES_DUE_REDUCED', 'PENALTY_LOCKED', 'PENALTY_REDUCTION_ADJUSTMENT', 'PENALTY_UNLOCKED', 'TAX_RATE_CHANGED', 'TERMS_CHANGED', 'TRANSFER', 'TRANSFER_ADJUSTMENT', 'WRITE_OFF', 'WRITE_OFF_ADJUSTMENT');

-- CreateTable
CREATE TABLE "LoanTransaction" (
    "id" SERIAL NOT NULL,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "fees_amount" DOUBLE PRECISION NOT NULL,
    "interest_amount" DOUBLE PRECISION NOT NULL,
    "penalty_amount" DOUBLE PRECISION NOT NULL,
    "principal_amount" DOUBLE PRECISION NOT NULL,
    "principal_balance" DOUBLE PRECISION NOT NULL,
    "amount" DOUBLE PRECISION NOT NULL,
    "comment" TEXT,
    "entry_date" TIMESTAMP(3) NOT NULL,
    "type" "loan_transaction_type" NOT NULL,
    "user_id" INTEGER NOT NULL,
    "loan_account_id" INTEGER NOT NULL,

    CONSTRAINT "LoanTransaction_pkey" PRIMARY KEY ("id")
);
